# Generated by Django 5.2.11 on 2026-02-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последнее уведомление"
            ),
        ),
    ]
